# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/



# chi-squared test for differences

peaCounts <- c(69, 31)
names(peaCounts) <- c("Smooth", "Wrinkled")
chisq.test(peaCounts, p=c(0.75,0.25))

# chi-squared test for association
treeFall <- matrix(c(10,3,5,12), nrow = 2, 
                  dimnames = list(treatment=c( "Control", "Shaken"),
                                  outcome=c("Fallen", "Standing")    ))
chisq.test(treeFall, correct=F)  # this one should match other software.

chisq.test(treeFall)  # the default is to apply continuity correction. 
### this does not agree with the Graphpad version....
# see here for explanation https://stats.stackexchange.com/questions/362517/when-to-switch-off-the-continuity-correction-in-chisq-test-function

barplot(treeFall, beside=T, legend.text=row.names(treeFall))
