# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/



?cor.test

heart_blood <- read.delim("data/heartRate_BP.tsv")

head(heart_blood)
dim(heart_blood)

plot(blood_pressure ~ heart_rate, data=heart_blood)
plot(heart_blood$heart_rate, heart_blood$blood_pressure, 
     xlab= "Heart Rate",ylab="Blood Pressure")

cor.test(heart_blood$heart_rate, heart_blood$blood_pressure)

# the value "cor" is Pearson's product moment correlation
# To get R^2, square this value.

testResult <- cor.test(heart_blood$heart_rate, heart_blood$blood_pressure)

?cor.test    #  use '?'  to find out about the Value returned by this function.

testResult$estimate
testResult$estimate ^ 2

# you can also extract the p-value
testResult$p.value
