# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/


age_sex <- read.delim("data/maleFemaleAge.tsv")

# how much data have we loaded 
dim(age_sex)

# 11 rows so OK to try and view it all
age_sex

# for larger data-sets it is useful to just check the top (or bottom) of the table
head(age_sex)
tail(age_sex)

# or one column at a time
age_sex[, 1]
# columns can also be called by name
age_sex[, "age"]
age_sex$age   # another way to do the same thing, this is a little faster to type

# or specific rows
age_sex[5:8, ]

summary(age_sex)

# for most data analysis involving categories (e.g. male/female) it is best to tell R that such data is a "factor"
age_sex$sex <- as.factor(age_sex$sex)
# this helps R know how to deal with this data and makes it easier to specify statistical models
summary(age_sex)

stripchart(age ~ sex, data = age_sex,  vertical =TRUE)
# only three male values are showing up. That's because there are overlapping values.
# these become visible if we activate jittering using the "method" parameter 
stripchart(age ~ sex, data = age_sex,  vertical =TRUE, method="jitter")

stripchart(age ~ sex, data = age_sex,  vertical =TRUE, method="jitter", ylim=c(0,80))

# typically we might have many more values than this and we would use a boxplot to summarise the distribution of the data within each factor level
boxplot(age ~ sex, data = age_sex)
# stripchart has a nice feature that you can add it to an existing plot.
stripchart(age ~ sex, data = age_sex,  vertical =TRUE, method="jitter", ylim=c(0,80), add=T)
