# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/


heights <- c(1.53, 1.65, 1.67, 1.59, 1.63, 1.72, 1.78, 1.69, 1.68, 1.60, 1.71, 1.68,1.66, 1.66, 1.62, 1.70)
mean(heights)
?mean

?sd
sd(heights)
# no built in function for s.e.m.
#se = sd / root(N)
sd(heights) / sqrt(length(heights))
?range
?quantile
?qt    # to get the critical t-value for a given degrees of freedom.
qt(1-(0.05/2), df=Inf)    # 95% of values fall with 1.96 S.E. of the mean. 

# for a sample, need to use the critical value based on samples size (degrees of freedom)

