# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/


# exponential decay using transformed variables ------------

blood_drug <- read.delim("data/blood_drug.tsv")

head(blood_drug)

# always a good idea to try and plot your data.
plot(Concentration_uM ~ Time_min , data = blood_drug)

# decrease over time but perhaps not linear.

# C = Co * exp(-λ * t)
# linearised as
# lnC = lnCo - (λ * t )
# note that time 't' is not logged

blood_drug$lnC <- log(blood_drug$Concentration_uM)
head(blood_drug)   # check this has been added

plot(lnC ~ Time_min , data = blood_drug)

# now fit a linear model
model <- lm(lnC ~ Time_min , data = blood_drug)

# what are the slope and intercept
coefficients(model)  #  Intercept and slope  

# but are these coefficients significantly different from zero?
summary(model)


# Calculate the initial concentration of the drug in the blood
# This you can work out from the Y-axis intercept, 
# which should be equal to lnC0. 
# Remember the inverse function for natural logs?

# in R there is function just for this
?exp()

model.int <- coefficients(model)[1]   # lnCo
model.slope <- coefficients(model)[2]   # also equal λ (lamda)
model.Co <- exp(model.int)   # initial value of C at time zero
model.lamda <- -model.slope
model.halfLife <- 0.693 / model.lamda  # a standard conversion factor 

test_x <- 1:30
plot(lnC ~ Time_min , data = blood_drug)
lines(test_x, predict(model, list(Time_min=test_x)), lty=2)

# now plot the original data using a decay curve with parameters we got from the linear-fit
plot(Concentration_uM ~ Time_min , data = blood_drug, xlim=c(0,30), ylim=c(0,model.Co))
test_y <- model.Co * exp(-test_x * model.lamda)   # equation for decay using our parameter estimates.
lines(test_x, test_y)



# Non-linear regression example 1 blood drug -------------------------------------


# repeat line-fitting for both blood_drug and enzyme_kinetic examples using non-linear regression

# Non-linear 1: blood drug (exponential decay)

model <- nls(Concentration_uM ~ Co * exp(-Time_min * b)  , data=blood_drug, 
             start=list(Co=100, b=0.1))  # Co  = starting concentration;  b= lambda

summary(model)
coefficients(model)
cor(blood_drug$Concentration_uM,predict(model))

plot(Concentration_uM ~ Time_min , data = blood_drug, xlim=c(0,30), ylim=c(0,100))
lines(blood_drug$Time_min, predict(model, list(Time_min=blood_drug$Time_min)),lty=2,col="red",lwd=3)

# extract specific parameters if needed directly from model (c.f. linear version above)
model.Co <- coefficients(model)[1]   # initial value of C at time zero
model.lamda <-  coefficients(model)[2] 
model.halfLife <- 0.693 / model.lamda  # a standard conversion factor 





# Further resources ------------------------
# Tutorials and guides
#  https://datascienceplus.com/first-steps-with-non-linear-regression-in-r/


