# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/


egg_mass <- read.delim("data/eggMass.tsv")

dim(egg_mass)  # how many rows and columns
head(egg_mass)

# always a good idea to try and plot your data.
plot(Mass ~ Days, data = egg_mass)

# now fit a linear model
model <- lm(Mass ~ Days, data = egg_mass)

# what are the slope and intercept
coefficients(model)  #  Intercept and slope  

# but are these coeffecicents significantly different from zero?
summary(model)

# you can capture some of these metrics (e.g. R-square value)
# see help pages for summary.lm(), which is the function that is called when you run 
# the generic summary() function is called on the output from lm()
?summary.lm
sm <- summary(model)
sm$r.squared

# the model coefficients (intercept and slope) can be used to put the line on the plot.
plot(Mass ~ Days, data = egg_mass)
abline(a= coefficients(model)[1], b=coefficients(model)[2])


