# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/



# load data from learning resources performance

learn_res <- read.delim("data/learningResources.tsv")

dim(learn_res)
head(learn_res)
summary(learn_res)
boxplot(learn_res)

kruskal.test(learn_res)

learn_res_long <- stack(learn_res)
learn_res_long   #  good but column names could be better

colnames(learn_res_long)   <- c("Score", "Treatment")

kruskal.test(learn_res_long)  #  this is wrong as, by default, it will try to compare one column with the other
# with 'long' format data, you should either explicitly state the groupings
# or use the 'formula' syntax

kruskal.test(Score ~ Treatment, data=learn_res_long) # formula syntax. 
kruskal.test(x=learn_res_long$Score, g=learn_res_long$Treatment) # separate data and group vectors.

# these two methods should both match the result given by the original 
kruskal.test(learn_res)

# OK, lets now capture the output and inspect it.

kt.result <- kruskal.test(learn_res)

summary(kt.result)   # not very useful here. 

kt.result$p.value
kt.result$data.name


#N.B. for two non-matched samples, can use the Wilcox.test or the Kruskal.test. 
# If the samples are paired (e.g. two different measurements from the same individuals, 
# then you MUST use the Wilcox.test
# Perhap think of the kruskal.test as the test for 3+ samples. 

