# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/


# R has some functions to generate random numbers following a given distribution
?Distributions

# as we are going to use some randomisation and want reproducable results, we need to fix the random number generator.
set.seed(90210)

x <- rnorm(50, mean=5)     
hist(x)
# test for normality
# check whether data is normal
# if not it may be worth transforming the data to make use of parametric tests.
shapiro.test(x)

y <- 10^x   # this is an inverse log transformation
hist(y, breaks=100)  # now very non-normal and positively skewed
# test for normality
shapiro.test(y)  

# try transforming the data using log.  Could also try using the square-root.
y_log <- log10(y)  # 

plot(x,y_log)

hist(y_log)
hist(x)  

# other transformations
?sqrt
# powers x^2 or x^3 for negative (right) skewed distributions
# arcsin(sqrt()) for 0-1 limited data or proportional data.