# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/



# Lineweaver-Burke plot example (using transformed variables) ------------------

enzyme_kinetic <- read.delim("data/enzyme_kinetic.tsv")

dim(enzyme_kinetic)

enzyme_kinetic

# always a good idea to try and plot your data.
plot(rate_v ~ conc_S , data = enzyme_kinetic)

#  [would be useful to show the fit of a linear model to this]

# the Lineweaver-Burk plot, which plots 1/v on the Y-axis 
# against 1/[S] on the X-axis

enzyme_kinetic$inv_S <- 1/enzyme_kinetic$conc_S
enzyme_kinetic$inv_v <- 1/enzyme_kinetic$rate_v

plot(inv_v ~ inv_S , data = enzyme_kinetic, xlab="1/[S]", ylab="1/v")

# now fit a linear model
model <- lm(inv_v ~ inv_S , data = enzyme_kinetic)

# what are the slope and intercept
coefficients(model)  #  Intercept and slope  

# but are these coeffecicents significantly different from zero?
summary(model)

# calculate Vmax and Km from the slope and intercept
# Again, some maths is required. 
# The Y-axis intercept will be 1/Vmax, so that allows you to calculate Vmax.
# Then, using that value for Vmax, you can calculate Km from the slope. 
# Remember that slope = Km/Vmax, so you can rearrange that to read Km = ...

model.int <- coefficients(model)[1]
model.Vmax <- 1/ model.int
model.slope <- coefficients(model)[2]
model.Km <- model.slope * model.Vmax



# Non-linear regression example 2 : Michaelis Menten kinetics ----------------------


#Michaelis Menten equation

#    v = (Vmax * S)  /  (Km  +  S) 

 plot(rate_v ~ conc_S , data = enzyme_kinetic)
# as per learning materials
model <- nls(rate_v ~ (Vmax * conc_S) / (Km + conc_S)  , data=enzyme_kinetic)
# as per Crawley's R book (and nowhere else?)
#model <- nls(rate_v ~ (Vmax * conc_S) / (1 + Km * conc_S)  , data=enzyme_kinetic)

# first, using parameters estimated (roughly) from plot.  
# Could also use parameters from linear model above.
model <- nls(rate_v ~ (Vmax * conc_S) / (Km + conc_S)  , data=enzyme_kinetic,
             start=list(Vmax=45, Km=5))


cor(enzyme_kinetic$rate_v,predict(model))

plot(rate_v ~ conc_S , data = enzyme_kinetic)
lines(enzyme_kinetic$conc_S,predict(model, list(conc_S=enzyme_kinetic$conc_S)),lty=2,col="red",lwd=3 )
coefficients(model)
summary(model)
# the coefficients suggest this model has a much higher Vmax than we started with
plot(rate_v ~ conc_S , data = enzyme_kinetic, ylim=c(0,100), xlim=c(0, 100))
lines(enzyme_kinetic$conc_S,predict(model, list(conc_S=enzyme_kinetic$conc_S)),lty=2,col="red",lwd=3 )
# could use more x points to give a finer line
plot(rate_v ~ conc_S , data = enzyme_kinetic, ylim=c(0,100), xlim=c(0, 100))
lines(0:100,predict(model, list(conc_S=0:100)),lty=2,col="red",lwd=3 )
abline(h=coefficients(model)[1], lty=2)





# Further resources ------------------------
# Tutorials and guides
#  https://datascienceplus.com/first-steps-with-non-linear-regression-in-r/
