# This is an R script demonstrating some simple data manipulation and statistical functions in R.
#  Lines beginning with '#' are comments (like this line)
#  Other lines are commands that you can run in R
# Start at the top and run each line of command in turn
# Pay attention to the output generated by each command.
# If you are new to using R please read my advice here:
#  https://github.com/davetgerrard/dataHandlingSkills_R/



#
Field_1 <- c( 8, 12, 15, 21, 25, 44, 44, 60)

Field_2 <- c( 2, 4, 5, 9, 12, 17, 19 )

boxplot(list(F1=Field_1, F2=Field_2))
#boxplot(Field_1, Field_2)
median(Field_1)
median(Field_2)

shapiro.test(Field_1)  # shapiro test has low power for <30 data points
shapiro.test(Field_2) # shapiro test has low power for <30 data points

wilcox.test(Field_1, Field_2)
?wilcox.test  # note that the default is paired = TRUE so we don't need to specify this.

skinDrug <- read.delim("data/skinDrugBeforeAfter.tsv")



wilcox.test(x= skinDrug$Score_before, y=skinDrug$Score_after, paired=T)




